import { M_PLUS_1 } from "next/font/google";
import Navbar from "../components/navbar";
import Providers from "@/lib/providers";
import { Box } from "@mui/material";
import Footer from "../components/footer";

const mPlus1 = M_PLUS_1({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
});

export const metadata = {
  title: "Viet Pham - Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={mPlus1.className}
        style={{
          display: "flex",
          justifyContent: "center",
          flexDirection: "column",
          alignItems: "center",
        }}
      >
        <Providers>
          <Navbar />
          <Box
            sx={{
              mt: 7,
              width: "100%",
              maxWidth: "650px",
            }}
          >
            {children}
          </Box>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
