import { M_PLUS_1 } from "next/font/google";
import Navbar from "../components/navbar";
import Providers from "@/lib/providers";

const mPlus1 = M_PLUS_1({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
});

export const metadata = {
  title: "Viet Pham - Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mPlus1.className}>
        <Providers>
          <main>
            <Navbar />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
